/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as MateriIndexRouteImport } from './routes/materi/index'
import { Route as MateriIdRouteImport } from './routes/materi/$id'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIndexRoute = MateriIndexRouteImport.update({
  id: '/materi/',
  path: '/materi/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdRoute = MateriIdRouteImport.update({
  id: '/materi/$id',
  path: '/materi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/materi/$id': typeof MateriIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi/': typeof MateriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/materi/$id': typeof MateriIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi': typeof MateriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/materi/$id': typeof MateriIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi/': typeof MateriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/materi/$id' | '/quiz/$id' | '/materi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/materi/$id' | '/quiz/$id' | '/materi'
  id: '__root__' | '/' | '/api/chat' | '/materi/$id' | '/quiz/$id' | '/materi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  MateriIdRoute: typeof MateriIdRoute
  QuizIdRoute: typeof QuizIdRoute
  MateriIndexRoute: typeof MateriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/': {
      id: '/materi/'
      path: '/materi'
      fullPath: '/materi/'
      preLoaderRoute: typeof MateriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id': {
      id: '/materi/$id'
      path: '/materi/$id'
      fullPath: '/materi/$id'
      preLoaderRoute: typeof MateriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  MateriIdRoute: MateriIdRoute,
  QuizIdRoute: QuizIdRoute,
  MateriIndexRoute: MateriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
